"""
scaling.py

Scale definitions for conceptual scaling in ConceptFlow.

What this module does
---------------------
This module defines scale classes used to transform many-valued attributes
into binary attributes suitable for Formal Concept Analysis (FCA).

A scale answers the question:

    "Given a value of some attribute, how should it be represented
    as one or more binary FCA attributes?"

For example:

- A nominal attribute such as "color" may be transformed into:
    color=red, color=blue, color=green

- An ordinal attribute such as "size" with levels [S, M, L] may be
  transformed into:
    size>=S, size>=M, size>=L

- A numeric attribute such as "price" may be transformed using thresholds:
    price>=10, price>=20, price>=50

Why this module exists
----------------------
Many-valued data is not directly usable as a formal context.
Conceptual scaling is the bridge from many-valued data to binary FCA data.

This module defines the scaling rules.
The actual application of those rules to a many-valued context belongs in
`conceptual_scaler.py`.

Design note
-----------
This is an original implementation for ConceptFlow.

The general architectural idea is consistent with standard FCA practice:
- many-valued contexts are represented separately
- scales define binary views on many-valued attributes
- a conceptual scaler applies those scales to produce a FormalContext

"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any

class Scale(ABC):
    """
    Abstract base class for all conceptual scales.

    A scale converts one many-valued attribute into one or more binary
    FCA attributes.
    """

    def __init__(self, source_attribute: str | int) -> None:
        if isinstance(source_attribute, int):
            self.source_attribute = f"x{source_attribute}"
        else:
            self.source_attribute = source_attribute

    @abstractmethod
    def binary_attributes(self, mvc) -> list[str]:
        """
        Return the binary attributes generated by this scale.
        """
        raise NotImplementedError

    @abstractmethod
    def encode_value(self, value: Any, mvc) -> dict[str, bool]:
        """
        Encode one many-valued entry as binary attributes.
        """
        raise NotImplementedError

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(source_attribute={self.source_attribute!r})"


class NominalScale(Scale):
    """
    Nominal scale for unordered categorical values.

    Example
    -------
    color = red becomes:

        color=red   True
        color=blue  False
        color=green False
    """

    def binary_attributes(self, mvc) -> list[str]:
        values = sorted(mvc.unique_values(self.source_attribute), key=str)
        return [f"{self.source_attribute}={value}" for value in values]

    def encode_value(self, value: Any, mvc) -> dict[str, bool]:
        """
        Encode one value using the vocabulary of ``mvc``.

        ``mvc`` should be the many-valued context this scale was fit on, not
        arbitrary transform-time data -- callers (e.g. ``ConceptualScaler``)
        are responsible for always passing the fit-time context here so the
        vocabulary (and therefore the generated attribute names) stays fixed
        between fit and transform.
        """
        attrs = self.binary_attributes(mvc)
        target = f"{self.source_attribute}={value}"

        if target not in attrs:
            raise ValueError(
                f'Value {value!r} for attribute "{self.source_attribute}" was '
                f"not part of the vocabulary this scale was fit on. Known "
                f"values: {sorted(mvc.unique_values(self.source_attribute), key=str)}."
            )

        return {attr: attr == target for attr in attrs}


class ContranominalScale(Scale):
    """
    Contranominal scale for unordered categorical values.

    This is the complement of a nominal scale.

    Example
    -------
    If color = red, then:

        color!=red   False
        color!=blue  True
        color!=green True
    """

    def binary_attributes(self, mvc) -> list[str]:
        values = sorted(mvc.unique_values(self.source_attribute), key=str)
        return [f"{self.source_attribute}!={value}" for value in values]

    def encode_value(self, value: Any, mvc) -> dict[str, bool]:
        """
        Encode one value using the vocabulary of ``mvc``.

        See ``NominalScale.encode_value`` for the fit-time-vs-transform-time
        contract ``mvc`` must satisfy here.
        """
        attrs = self.binary_attributes(mvc)
        target = f"{self.source_attribute}!={value}"

        if target not in attrs:
            raise ValueError(
                f'Value {value!r} for attribute "{self.source_attribute}" was '
                f"not part of the vocabulary this scale was fit on. Known "
                f"values: {sorted(mvc.unique_values(self.source_attribute), key=str)}."
            )

        return {attr: attr != target for attr in attrs}


class DichotomicScale(Scale):
    """
    Explicit two-valued scale.

    This is useful for binary attributes such as:

        yes/no
        true/false
        present/absent

    It is similar to a nominal scale with exactly two values, but more explicit.
    """

    def __init__(
        self,
        source_attribute: str | int,
        true_value: Any = True,
        false_value: Any = False,
    ) -> None:
        super().__init__(source_attribute)

        if true_value == false_value:
            raise ValueError("true_value and false_value must be different.")

        self.true_value = true_value
        self.false_value = false_value

    def binary_attributes(self, mvc) -> list[str]:
        return [
            f"{self.source_attribute}={self.true_value}",
            f"{self.source_attribute}={self.false_value}",
        ]

    def encode_value(self, value: Any, mvc) -> dict[str, bool]:
        if value not in {self.true_value, self.false_value}:
            raise ValueError(
                f"Value {value!r} is not valid for DichotomicScale "
                f'of attribute "{self.source_attribute}". '
                f"Expected {self.true_value!r} or {self.false_value!r}."
            )

        return {
            f"{self.source_attribute}={self.true_value}": value == self.true_value,
            f"{self.source_attribute}={self.false_value}": value == self.false_value,
        }


class OrdinalScale(Scale):
    """
    Ordinal scale for ordered categorical values.

    Parameters
    ----------
    source_attribute:
        Attribute to scale.

    levels:
        Ordered values from lowest to highest.

    mode:
        - "ge": generate attributes like attr>=level
        - "le": generate attributes like attr<=level
        - "exact": generate attributes like attr=level
    """

    def __init__(
        self,
        source_attribute: str | int,
        levels: list[Any],
        mode: str = "ge",
    ) -> None:
        super().__init__(source_attribute)

        if not levels:
            raise ValueError("OrdinalScale requires a non-empty list of levels.")
        if len(set(levels)) != len(levels):
            raise ValueError("OrdinalScale levels must be unique.")
        mode = mode.lower()
        if mode not in {"ge", "le", "exact"}:
            raise ValueError('OrdinalScale mode must be "ge", "le", or "exact".')

        self.levels = list(levels)
        self.mode = mode
        self._rank = {
            level: i
            for i, level in enumerate(self.levels)
        }

    def binary_attributes(self, mvc) -> list[str]:
        if self.mode == "ge":
            return [f"{self.source_attribute}>={level}" for level in self.levels]

        if self.mode == "le":
            return [f"{self.source_attribute}<={level}" for level in self.levels]

        return [f"{self.source_attribute}={level}" for level in self.levels]

    def encode_value(self, value: Any, mvc) -> dict[str, bool]:
        if value not in self._rank:
            raise ValueError(
                f'Value {value!r} is not part of the declared levels '
                f'for attribute "{self.source_attribute}".'
            )

        value_rank = self._rank[value]

        if self.mode == "ge":
            return {
                f"{self.source_attribute}>={level}": value_rank >= self._rank[level]
                for level in self.levels
            }

        if self.mode == "le":
            return {
                f"{self.source_attribute}<={level}": value_rank <= self._rank[level]
                for level in self.levels
            }

        return {
            f"{self.source_attribute}={level}": value == level
            for level in self.levels
        }


class ThresholdScale(Scale):
    """
    Threshold-based scale for numeric values.

    Example
    -------
    score = 45, thresholds = [20, 50, 80]

    gives:

        score>=20 True
        score>=50 False
        score>=80 False
    """

    def __init__(self, source_attribute: str | int, thresholds: list[float]) -> None:
        super().__init__(source_attribute)

        if not thresholds:
            raise ValueError("ThresholdScale requires a non-empty list of thresholds.")

        sorted_thresholds = sorted(thresholds)

        if len(set(sorted_thresholds)) != len(sorted_thresholds):
            raise ValueError("ThresholdScale thresholds must be unique.")

        self.thresholds = sorted_thresholds

    def binary_attributes(self, mvc) -> list[str]:
        return [f"{self.source_attribute}>={threshold}" for threshold in self.thresholds]

    def encode_value(self, value: Any, mvc) -> dict[str, bool]:
        try:
            return {
                f"{self.source_attribute}>={threshold}": value >= threshold
                for threshold in self.thresholds
            }
        except TypeError as exc:
            raise TypeError(
                f'Value {value!r} for attribute "{self.source_attribute}" '
                "cannot be compared with numeric thresholds."
            ) from exc


class InterordinalScale(Scale):
    """
    Interordinal scale for ordered values.

    This combines <= and >= attributes.

    Example
    -------
    size = M, levels = [S, M, L]

    gives:

        size<=S False
        size<=M True
        size<=L True
        size>=S True
        size>=M True
        size>=L False
    """

    def __init__(self, source_attribute: str | int, levels: list[Any]) -> None:
        super().__init__(source_attribute)

        if not levels:
            raise ValueError("InterordinalScale requires a non-empty list of levels.")
        if len(set(levels)) != len(levels):
            raise ValueError("InterordinalScale levels must be unique.")

        self.levels = list(levels)
        self._rank = {
            level: i
            for i, level in enumerate(self.levels)
        }

    def binary_attributes(self, mvc) -> list[str]:
        lower = [f"{self.source_attribute}<={level}" for level in self.levels]
        upper = [f"{self.source_attribute}>={level}" for level in self.levels]
        return lower + upper

    def encode_value(self, value: Any, mvc) -> dict[str, bool]:
        if value not in self._rank:
            raise ValueError(
                f'Value {value!r} is not part of the declared levels '
                f'for attribute "{self.source_attribute}".'
            )

        value_rank = self._rank[value]
        encoding: dict[str, bool] = {}

        for level in self.levels:
            level_rank = self._rank[level]
            encoding[f"{self.source_attribute}<={level}"] = value_rank <= level_rank
            encoding[f"{self.source_attribute}>={level}"] = value_rank >= level_rank

        return encoding


class GeneralScale(Scale):
    """
    General custom scale defined by an explicit value-to-attributes mapping.

    This is useful for paper-style or domain-specific conceptual scales.

    Example
    -------
    pH_level = dangerous may imply both:

        dangerous pH
        pathological pH

    while pH_level = pathological implies only:

        pathological pH

    This cannot be represented as a simple nominal scale.
    """

    def __init__(
        self,
        source_attribute: str | int,
        mapping: dict[Any, set[str] | list[str] | tuple[str, ...]],
        attribute_order: list[str] | None = None,
    ) -> None:
        super().__init__(source_attribute)

        if not mapping:
            raise ValueError("GeneralScale requires a non-empty mapping.")

        normalized_mapping: dict[Any, frozenset[str]] = {
            value: frozenset(attrs)
            for value, attrs in mapping.items()
        }

        if attribute_order is None:
            attribute_order = sorted(
                {
                    attr
                    for attrs in normalized_mapping.values()
                    for attr in attrs
                },
                key=str,
            )
        else:
            used_attributes = {
                attr
                for attrs in normalized_mapping.values()
                for attr in attrs
            }

            missing = used_attributes - set(attribute_order)
            if missing:
                raise ValueError(
                    "attribute_order is missing attributes used in mapping: "
                    f"{sorted(missing)}"
                )

        self.mapping = normalized_mapping
        self.attribute_order = list(attribute_order)

    def binary_attributes(self, mvc) -> list[str]:
        return list(self.attribute_order)

    def encode_value(self, value: Any, mvc) -> dict[str, bool]:
        if value not in self.mapping:
            raise ValueError(
                f"Value {value!r} is not defined in GeneralScale "
                f'for attribute "{self.source_attribute}".'
            )

        active_attributes = self.mapping[value]

        return {
            attr: attr in active_attributes
            for attr in self.attribute_order
        }